name: 日時順位確認
on:
  schedule:
    # JST 10:05
    - cron: '5 1 * * *'
  workflow_dispatch:


jobs:
  rank-check:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 依存関係のインストール
        run: npm install

      - name: Puppeteer 依存ライブラリのインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates \
            fonts-liberation \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            lsb-release \
            wget \
            xdg-utils

      - name: 必要なディレクトリの作成
        run: |
          mkdir -p result
          mkdir -p screenshots

      - name: ランクチェック実行
        run: node index.js
        env:
          RANK_CHECKER_EMAIL: ${{ secrets.rank_checker_email }}
          RANK_CHECKER_PASSWORD: ${{ secrets.rank_checker_password }}
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
          SPREADSHEET_ID: ${{ secrets.spreadsheet_id }}
          PERCENT_SPREADSHEET_ID: ${{ secrets.percent_spreadsheet_id }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.google_application_credentials }}
          ENABLE_GOOGLE_SHEETS: true
      - name: Slack通知
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'ランクチェック完了 :rocket:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always() # 成功しても失敗しても通知ank-check